### PR TITLE
Fix Java determination and support JAVA_HOME (#103)

### LINKED ISSUE #103: Error: write EPIPE when running dukat on .d.ts file
I have installed dukat using `npm install -g dukat`, Win10
Running `dukat typings.ts` in cmd outputs the following:
```js
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:78:25)
    at writeGeneric (internal/stream_base_commons.js:73:3)
    at Socket._writeGeneric (net.js:713:5)
    at Socket._write (net.js:725:8)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Socket.Writable.write (_stream_writable.js:299:11)
    at Readable.ondata (_stream_readable.js:693:20)
    at Readable.emit (events.js:198:13)
    at Readable.read (_stream_readable.js:491:10)
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at Socket.onerror (_stream_readable.js:717:7)
    at Socket.emit (events.js:203:15)
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:430:5)
    at onwrite (_stream_writable.js:461:5)
    at _destroy (internal/streams/destroy.js:49:7)
    at Socket._destroy (net.js:613:3)
    at Socket.destroy (internal/streams/destroy.js:37:8)
    at afterWriteDispatched (internal/stream_base_commons.js:78:17)
```

### PR DESCRIPTION
**Pull request by Vampire**
fixes #103

### CODE REVIEW

File: node-package/bin/dukat-cli.js [hunk 1]
```diff
@@ -23,18 +28,37 @@ function run(command, args) {
...
+    } catch (error) {
+        printError(error)
+        if (javaHome) {
+            printInvalidJavaHome();
+        } else {
             printNoJava();
-            process.exit(error.code);
         }
-    });
+        process.exit(1);
```
Comment (Schahen) [inline node-package/bin/dukat-cli.js:59]: It seems to me no harm to pass actual error.code rather than 1 - is there any reasoning behind this decision?

File: node-package/bin/dukat-cli.js [hunk 2]
```diff
@@ -23,18 +28,37 @@ function run(command, args) {
...
 }
 
-function guardJavaExists() {
-    exec("java -version", function (error, stdout, stderr) {
-        if (error) {
+function findJavaExecutable() {
+    var javaHome = process.env.JAVA_HOME
+    var result = javaHome ? path.join(javaHome, "bin", "java") : "java"
+    try {
+        execSync('"' + result + "\" -version", {
```
Comment (Schahen) [inline node-package/bin/dukat-cli.js:49]: I'm against of this approach so let's discuss. One thing is to rely on JAVA_HOME - that's definitely an improvement. 
The other thing is to check java -v every time we are calling dukat. 
May be there's sense to do it in some sort of debug or diagnostics mode but each time seems to me be an overkill.

File: node-package/bin/dukat-cli.js (hunk 1 above)
Comment (Vampire) [reply node-package/bin/dukat-cli.js:59]: The reason was, that `error.code` is `undefined`, at least in the cases I looked at it.
There is a property `error.status`, but I was unsure whether this represents the exit code.
Thus I decided to just always use 1.

File: node-package/bin/dukat-cli.js (hunk 2 above)
Comment (Vampire) [reply node-package/bin/dukat-cli.js:49]: To be honest, that approach ist not by me, but by you (or whoever orginally wrote that code).
I didn't change that logic.
The only change I made is, that JAVA_HOME is considered for finding Java.
`findJavaExecutable` ist called at the exact same one place `guardJavaExists` was called before.
I just changed its name and made it return the path to be used to call Java later on.

Comment (Schahen) [reply node-package/bin/dukat-cli.js:49]: A-ha-ha, now I feel **very** stupid! Sorry for misinterpreting, I apologize ))
This PR looks good to me. Thank you for your contribution. I guess it's time to introduce a contributors list - will create task on this.
